# Generated by Django 5.2.4 on 2025-08-02 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
        ('usuario', '0003_remove_usuario_fecha_crea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_intervencion', models.CharField(max_length=50, verbose_name='Tipo de Intervención')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('fecha_intervencion', models.DateField(verbose_name='Fecha de Intervención')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Intervención')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente', verbose_name='Expediente')),
                ('user_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creo registro')),
                ('user_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modifico registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Usuario')),
                ('tipo_intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervencion.tipointervencion', verbose_name='Tipo de Intervención')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
