# Generated by Django 5.2.4 on 2025-08-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0003_delete_estadoarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_intervencion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de intervención')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de intervención',
                'verbose_name_plural': 'Tipos de intervenciones',
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intervencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la intervención')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencion_expediente', to='expediente.expediente')),
            ],
        ),
    ]
