# Generated by Django 5.2.4 on 2025-08-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_intervencion', models.CharField(max_length=50, verbose_name='Tipo de Intervención')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intervencion', models.DateField(verbose_name='Fecha de Intervención')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Intervención')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente', verbose_name='Expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Usuario')),
                ('tipo_intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervencion.tipointervencion', verbose_name='Tipo de Intervención')),
            ],
        ),
    ]
