# Generated by Django 5.2.4 on 2025-08-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervencion', '0001_initial'),
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencion_profesional', to='profesional.profesional'),
        ),
        migrations.AddField(
            model_name='intervencion',
            name='tipo_intervencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencion_tipo_intervencion', to='intervencion.tipointervencion'),
        ),
    ]
