# Generated by Django 5.2.4 on 2025-08-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervencion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervencion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='fecha_crea',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='fecha_modifica',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='user_crea',
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='user_modifica',
        ),
    ]
