# Generated by Django 5.2.4 on 2025-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervencion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervencion',
            options={'ordering': ['-fecha_intervencion'], 'verbose_name': 'Intervención', 'verbose_name_plural': 'Intervenciones'},
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='fecha_intervencion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la intervención'),
        ),
    ]
