# Generated by Django 5.2.4 on 2025-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(help_text='Nombre de la provincia', max_length=100, verbose_name='Provincia')),
            ],
        ),
    ]
