# Generated by Django 5.2.4 on 2025-07-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genero_nivel_educativo_pais_sede_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['pais'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
    ]
