# Generated by Django 5.2.4 on 2025-08-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='Localidad',
            new_name='localidad',
        ),
        migrations.AddField(
            model_name='sede',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='sede',
            name='direccion_depto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dto.'),
        ),
        migrations.AddField(
            model_name='sede',
            name='direccion_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='sede',
            name='direccion_piso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='sede',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
