# Generated by Django 5.2.4 on 2025-07-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pais_options_alter_provincia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_profesional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Área profesional')),
            ],
            options={
                'verbose_name': 'Área profesional',
                'verbose_name_plural': 'Áreas profesionales',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.AddField(
            model_name='sede',
            name='Localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sede_localidad', to='core.localidad', verbose_name='Localidad'),
        ),
    ]
