# Generated by Django 5.2.4 on 2025-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_localidad_sede_localidad_sede_direccion_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Nombre abreviado'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de postal'),
        ),
    ]
