# Generated by Django 5.2.4 on 2025-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_localidad_abreviatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Nombre abreviado'),
        ),
    ]
