# Generated by Django 5.2.4 on 2025-08-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clientelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidad',
            old_name='nombre_abreviado',
            new_name='abreviatura',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='codigo_area',
        ),
        migrations.AddField(
            model_name='localidad',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código de postal'),
        ),
    ]
