# Generated by Django 5.2.4 on 2025-08-14 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sede_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sede_localidad', to='core.localidad', verbose_name='Localidad'),
        ),
    ]
