# Generated by Django 5.2.4 on 2025-08-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sede_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='abreviatura',
        ),
    ]
