# Generated by Django 5.2.4 on 2025-08-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_localidad_abreviatura'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        ),
    ]
