# Generated by Django 5.2.4 on 2025-08-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_archivo', models.CharField(max_length=50, verbose_name='Estado del Archivo')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado del archivo',
                'verbose_name_plural': 'Estado de los archivos',
            },
        ),
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_expediente', models.CharField(max_length=100, verbose_name='Estado el expediente')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado del expediente',
                'verbose_name_plural': 'Estado de los expedientes',
            },
        ),
        migrations.CreateModel(
            name='GrupoEtario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_etario', models.CharField(max_length=50, verbose_name='Grupo Etario')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo Etario',
                'verbose_name_plural': 'Grupos etarios',
            },
        ),
        migrations.CreateModel(
            name='MedioIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_ingreso', models.CharField(max_length=50, verbose_name='Medio de Ingreso')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de Ingreso',
                'verbose_name_plural': 'Medios de Ingresos',
            },
        ),
        migrations.CreateModel(
            name='ResumenIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_intervencion', models.CharField(max_length=50, verbose_name='Resumen de Intervención')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resumen de Intervención',
                'verbose_name_plural': 'Resumenes de intervenciones',
            },
        ),
        migrations.CreateModel(
            name='TipoPatrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_patrocinio', models.CharField(max_length=50, verbose_name='Tipo de Patrocinio')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de patrocinio',
                'verbose_name_plural': 'Tipos de patrocinios',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=50, verbose_name='Tipo de Solicitud')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de solicitud',
                'verbose_name_plural': 'Tipos de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_juzgado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Juzgado')),
                ('fecha_de_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('cuij', models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIJ')),
                ('clave_sisfe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave SISFE')),
                ('situacion_habitacional_hist', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situación habitacional histórica')),
                ('numero', models.PositiveIntegerField(verbose_name='Guarda el número de expediente generado')),
                ('anio', models.PositiveIntegerField(default=2025, verbose_name='Guarda el año obtenido por la función')),
                ('abreviatura', models.CharField(max_length=4)),
                ('identificador', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Identificador del Expediente')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha en que se creó')),
                ('expediente_fisico', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localidad')),
                ('grupo_etario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expdiente_grupo_etario', to='expediente.grupoetario')),
                ('medio_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.medioingreso')),
                ('resumen_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.resumenintervencion')),
                ('tipo_patrocinio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.tipopatrocinio')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.tiposolicitud')),
            ],
            options={
                'unique_together': {('numero', 'anio', 'abreviatura')},
            },
        ),
    ]
