# Generated by Django 5.2.4 on 2025-08-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estado_expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expediente_estado_expediente', to='expediente.estadoexpediente'),
        ),
    ]
