# Generated by Django 5.2.4 on 2025-08-05 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nombre_abreviado_localidad_abreviatura_and_more'),
        ('expediente', '0002_remove_expediente_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_ingreso', models.CharField(max_length=50, verbose_name='Medio de Ingreso')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de Ingreso',
                'verbose_name_plural': 'Medios de Ingresos',
            },
        ),
        migrations.DeleteModel(
            name='MediosIngreso',
        ),
        migrations.AddField(
            model_name='expediente',
            name='abreviatura',
            field=models.CharField(default='NA', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='anio',
            field=models.PositiveIntegerField(default=2025, verbose_name='Guarda el año obtenido por la función'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='expediente_fisico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha en que se creó'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='grupo_etario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expdiente_grupo_etario', to='expediente.grupoetario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='identificador',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True, verbose_name='Identificador del Expediente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Guarda el número de expediente generado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='resumen_intervencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.resumenintervencion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_patrocinio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.tipopatrocinio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expediente.tiposolicitud'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together={('numero', 'anio', 'abreviatura')},
        ),
        migrations.AddField(
            model_name='expediente',
            name='medio_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.medioingreso'),
        ),
    ]
