# Generated by Django 5.2.4 on 2025-08-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_expediente_estado_expediente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoArchivo',
        ),
    ]
