# Generated by Django 5.2.4 on 2025-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_medioingreso_delete_mediosingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_archivo', models.CharField(max_length=50, verbose_name='Estado del Archivo')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado del archivo',
                'verbose_name_plural': 'Estado de los archivos',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='clave_sisfe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave SISFE'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='cuij',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIJ'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_de_juzgado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Juzgado'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_de_recepcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='situacion_habitacional_hist',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situación habitacional histórica'),
        ),
    ]
