# Generated by Django 5.2.4 on 2025-08-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rol'),
        ('expediente', '0003_delete_estadoarchivo'),
        ('persona', '0002_alter_persona_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedientePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepersona_expediente', to='expediente.expediente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepersona_persona', to='persona.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepersona_rol', to='core.rol')),
            ],
        ),
    ]
