# Generated by Django 5.2.4 on 2025-08-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rol'),
        ('expediente', '0004_expedientepersona'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteinstitucion_expediente', to='expediente.expediente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteinstitucion_institucion', to='institucion.institucion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteinstitucion_rol', to='core.rol')),
            ],
        ),
    ]
