# Generated by Django 5.2.4 on 2025-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_expedienteinstitucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='edad_persona',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Persona'),
        ),
    ]
