# Generated by Django 5.2.4 on 2025-08-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sede_abreviatura'),
        ('expediente', '0006_expediente_edad_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sede', verbose_name='Sede'),
            preserve_default=False,
        ),
    ]
