# Generated by Django 5.2.4 on 2025-08-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sede_abreviatura'),
        ('expediente', '0007_expediente_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expediente_localidad', to='core.localidad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sede'),
        ),
    ]
