# Generated by Django 5.2.4 on 2025-08-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0008_alter_expediente_localidad_alter_expediente_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='localidad',
        ),
    ]
