# Generated by Django 5.2.4 on 2025-08-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sede_abreviatura'),
        ('expediente', '0009_remove_expediente_localidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'ordering': ['-anio', '-numero']},
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='clave_sisfe',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='cuij',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='estado_expediente',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='fecha_de_juzgado',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='fecha_de_recepcion',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='situacion_habitacional_hist',
        ),
        migrations.AddField(
            model_name='expediente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='situacion_habitacional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='anio',
            field=models.PositiveIntegerField(default=2025, verbose_name='Año del expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='edad_persona',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='grupo_etario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_grupo_etario', to='expediente.grupoetario'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='identificador',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Identificador del expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número de expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sede', verbose_name='Sede'),
        ),
    ]
