# Generated by Django 5.2.4 on 2025-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0010_alter_expediente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='abreviatura',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
