# Generated by Django 5.2.4 on 2025-08-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sede_abreviatura'),
        ('expediente', '0011_alter_expediente_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='abreviatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_abreviatura_sede', to='core.sede'),
        ),
    ]
