# Generated by Django 5.2.4 on 2025-08-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0012_alter_expediente_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estado_expediente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='expediente_estado_expediente', to='expediente.estadoexpediente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente',
            name='abreviatura',
            field=models.CharField(max_length=4, verbose_name='Abreviatura'),
        ),
    ]
