# Generated by Django 5.2.4 on 2025-08-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0013_expediente_estado_expediente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='situacion_habitacional',
            new_name='situacion_habitacional_hist',
        ),
    ]
