# Generated by Django 5.2.4 on 2025-08-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0014_rename_situacion_habitacional_expediente_situacion_habitacional_hist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha_creacion',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaviones'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='situacion_habitacional_hist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Situación habitacional historica'),
        ),
    ]
