# Generated by Django 5.2.4 on 2025-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0015_alter_expediente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='clave_sisfe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave SISFE'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='cuij',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIJ'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_de_juzgado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Juzgado'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_de_recepcion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
    ]
