# Generated by Django 5.2.4 on 2025-08-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0016_expediente_clave_sisfe_expediente_cuij_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='documentos/expedientes/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.expediente')),
            ],
        ),
    ]
