# Generated by Django 5.2.4 on 2025-09-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0017_expedientedocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha_de_juzgado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Juzgado'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_de_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AlterField(
            model_name='expedientedocumento',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True),
        ),
    ]
