# Generated by Django 5.2.4 on 2025-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250820_2030'),
        ('expediente', '0018_alter_expediente_fecha_de_juzgado_and_more'),
        ('institucion', '0001_initial'),
        ('persona', '0004_alter_persona_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expedienteinstitucion',
            constraint=models.UniqueConstraint(fields=('expediente', 'institucion', 'rol'), name='unique_expediente_institucion_rol'),
        ),
        migrations.AddConstraint(
            model_name='expedientepersona',
            constraint=models.UniqueConstraint(fields=('expediente', 'persona', 'rol'), name='unique_expediente_persona_rol'),
        ),
    ]
