# Generated by Django 5.2.4 on 2025-07-31 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_areaprofesional_profesion_sede_localidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('fecha_modifica', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('area_profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional_area_profesional', to='core.areaprofesional', verbose_name='Área profesional')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_profesion', to='core.profesion', verbose_name='Profesión')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_sede', to='core.sede', verbose_name='Sede')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_documento', verbose_name='Documento tipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('user_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_crea', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creo registro')),
                ('user_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_modifica', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modifico registro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
