# Generated by Django 5.2.4 on 2025-08-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_crea',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_modifica',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_crea',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_modifica',
        ),
    ]
