# Generated by Django 5.2.4 on 2025-08-13 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sede_abreviatura'),
        ('usuario', '0002_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sede', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
