# Generated by Django 5.2.4 on 2025-08-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_customuser_localidad_customuser_sede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI'),
        ),
    ]
