# Generated by Django 5.2.4 on 2025-08-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('direccion_calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle')),
                ('direccion_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('direccion_piso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso')),
                ('direccion_depto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dto.')),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de nacimiento')),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación')),
                ('posee_cobertura_salud', models.BooleanField(default=False, verbose_name='Posee cobertura?')),
                ('cobertura_salud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cobertura de salud')),
                ('posee_grupo_apoyo', models.BooleanField(default=False, verbose_name='Posee grupo?')),
                ('grupo_apoyo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo de apoyo')),
                ('derecho_seguridad_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Derecho a la seguridad social')),
                ('administra_recursos', models.BooleanField(default=False, verbose_name='Administra recursos?')),
                ('carnet_discapacidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Carnet de discapacidad')),
                ('situacion_habitacional', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situación habitacional')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_genero', to='core.genero', verbose_name='Género')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_localidad', to='core.localidad', verbose_name='Localidad')),
                ('nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_nivel_educativo', to='core.nivel_educativo', verbose_name='Nivel educativo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_tipo_documento', to='core.tipo_documento', verbose_name='Documento tipo')),
            ],
        ),
    ]
