# Generated by Django 5.2.4 on 2025-08-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(blank=True, help_text='Localidad donde habita actualmete', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_localidad', to='core.localidad', verbose_name='Localidad'),
        ),
    ]
