# Generated by Django 5.2.4 on 2025-08-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='direccio_calle',
            new_name='direccion_calle',
        ),
    ]
