# Generated by Django 5.2.4 on 2025-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_rename_direccio_calle_persona_direccion_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion_depto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dto.'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='posee_cobertura_salud',
            field=models.BooleanField(default=False, verbose_name='Posee cobertura?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='posee_grupo_apoyo',
            field=models.BooleanField(default=False, verbose_name='Posee grupo?'),
        ),
    ]
