# Generated by Django 5.2.4 on 2025-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
