# Generated by Django 5.2.4 on 2025-09-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': [('puede_crear_persona', 'Puede crear una persona')]},
        ),
    ]
