# Generated by Django 5.2.4 on 2025-08-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_expedienteinstitucion'),
        ('internacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacion',
            name='expediente_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacion_expedienteinstitucion', to='expediente.expedienteinstitucion'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de alta o derivación'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='fecha_cumplimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cumplimiento'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='fecha_internacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de internación'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='intento_suicidio',
            field=models.BooleanField(default=False, verbose_name='Intento de suicidio?'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='modalidad_suicidio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacion_modalidad_suicidio', to='internacion.modalidadsuicidio'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_alta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacion_motivo_alta', to='internacion.motivoalta'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='motivo_internacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacion_motivo_internacion', to='internacion.motivointernacion'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='posse_adiccion',
            field=models.BooleanField(default=False, verbose_name='Posee adicciones?'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='requisitos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='tipo_adiccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacion_tipo_adiccion', to='internacion.tipoadiccion'),
        ),
    ]
