# Generated by Django 5.2.4 on 2025-09-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0002_internacion_expediente_institucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInternacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_internacion', models.CharField(max_length=50, verbose_name='Tipo de Internación')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='internacion',
            name='tipo_internacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internacion_tipo_internacion', to='internacion.tipointernacion'),
        ),
    ]
