# Generated by Django 5.2.4 on 2025-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0003_tipointernacion_internacion_tipo_internacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidadsuicidio',
            options={'ordering': ['-id'], 'verbose_name': 'Modalidad de Suicidio', 'verbose_name_plural': 'Modalidades de Suicidio'},
        ),
        migrations.AlterModelOptions(
            name='motivoalta',
            options={'ordering': ['-id'], 'verbose_name': 'Motivo de Alta', 'verbose_name_plural': 'Motivos de Alta'},
        ),
        migrations.AlterModelOptions(
            name='motivointernacion',
            options={'ordering': ['-id'], 'verbose_name': 'Motivo de Internación', 'verbose_name_plural': 'Motivos de Internación'},
        ),
        migrations.AlterModelOptions(
            name='tipoadiccion',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de Adicción', 'verbose_name_plural': 'Tipos de Adicción'},
        ),
        migrations.AlterModelOptions(
            name='tipointernacion',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de Internación', 'verbose_name_plural': 'Tipos de Internación'},
        ),
        migrations.AddField(
            model_name='internacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
