# Generated by Django 5.2.4 on 2025-09-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0004_alter_modalidadsuicidio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacion',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
