# Generated by Django 5.2.4 on 2025-09-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0005_internacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacion',
            name='fecha_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cumplimiento'),
        ),
    ]
