# Generated by Django 5.2.4 on 2025-09-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0006_alter_internacion_fecha_cumplimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internacion',
            old_name='posse_adiccion',
            new_name='posee_adiccion',
        ),
    ]
