# Generated by Django 5.2.4 on 2025-07-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_areaprofesional_profesion_sede_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_institucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Institución')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Institución',
                'verbose_name_plural': 'Tipos de Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institución')),
                ('domicilio_calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicilio Calle')),
                ('domicilio_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Domicilio Número')),
                ('domicilio_piso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Domicilio Piso')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('localidad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institucion_localidad', to='core.localidad', verbose_name='Localidad')),
                ('tipo_institucion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_tipo_institucion', to='institucion.tipoinstitucion', verbose_name='Tipo de Institución')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
    ]
