# Generated by Django 5.2.4 on 2025-08-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='domicilio_depto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Domicilio Depto'),
        ),
    ]
