# Generated by Django 5.2.4 on 2025-08-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='tipo_documento',
        ),
    ]
