# Generated by Django 5.2.4 on 2025-09-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0002_remove_profesional_sede_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
    ]
